import eslint from '@eslint/js';
import prettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'coverage/**',
      'node_modules/**',
      '.wrangler/**',
      'migrations/**',
      // Generated by `wrangler types`; regenerated by `npm run check`.
      'worker-configuration.d.ts',
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Type imports must be explicit so type-stripping never leaves a dead require.
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      // Escape hatches are a review conversation, not a local decision.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      // Unhandled rejections in a request handler silently drop work.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Logging goes through the Fastify/Pino logger so it stays structured and redacted.
      'no-console': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Enums are not erasable syntax. Use a union type or `as const` object.',
        },
        {
          selector: 'TSModuleDeclaration[kind="namespace"]',
          message: 'Namespaces are not erasable syntax. Use ES modules.',
        },
      ],
    },
  },
  {
    // Ambient declaration files exist to merge into global interfaces, which
    // requires `declare namespace`. Nothing here is emitted, so erasability
    // does not apply.
    files: ['**/*.d.ts'],
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // Tests may reach for sharper tools than production code.
    files: ['test/**/*.ts', 'src/**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
  {
    files: ['eslint.config.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Build-time tooling, run by `npm run check` on the developer's machine and
    // in CI — never bundled into the Worker. So Node globals are legitimate
    // here, and `console` is the only output channel a CLI has. It is outside
    // tsconfig's `include` for the same reason, hence no type-aware linting.
    files: ['scripts/**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: { console: 'readonly', process: 'readonly' },
    },
    rules: {
      'no-console': 'off',
    },
  },
  prettier,
);
